//
//  GoalieStyleKit.swift
//  Goalie
//
//  Created by Gregory Klein on 1/5/16.
//  Copyright (c) 2016 Incipia. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class GoalieStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfGoalieSleeping: UIImage?
        static var goalieSleepingTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawGoalieSleeping() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let fillColor = UIColor(red: 0.340, green: 0.318, blue: 0.650, alpha: 1.000)
        let fillColor2 = UIColor(red: 0.225, green: 0.211, blue: 0.504, alpha: 1.000)
        let fillColor3 = UIColor(red: 0.191, green: 0.180, blue: 0.422, alpha: 1.000)
        let fillColor4 = UIColor(red: 0.965, green: 0.752, blue: 0.845, alpha: 0.200)
        let fillColor5 = UIColor(red: 0.099, green: 0.298, blue: 0.314, alpha: 0.200)

        //// Image Declarations
        let image = UIImage(named: "image.png")!

        //// Group 2
        //// Group 3
        //// Group 4
        //// Group 5
        //// _Image1 Drawing
        let _Image1Path = UIBezierPath(rect: CGRectMake(0, 0, 150, 195))
        CGContextSaveGState(context)
        _Image1Path.addClip()
        CGContextScaleCTM(context, 1, -1)
        CGContextDrawTiledImage(context, CGRectMake(0, 0, image.size.width, image.size.height), image.CGImage)
        CGContextRestoreGState(context)




        //// Group 6
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(120.4, 143.04))
        bezierPath.addCurveToPoint(CGPointMake(134.3, 105.44), controlPoint1: CGPointMake(129.1, 132.74), controlPoint2: CGPointMake(134.3, 119.64))
        bezierPath.addCurveToPoint(CGPointMake(134.3, 105.04), controlPoint1: CGPointMake(134.3, 105.34), controlPoint2: CGPointMake(134.3, 105.14))
        bezierPath.addCurveToPoint(CGPointMake(130.8, 84.84), controlPoint1: CGPointMake(134.3, 98.24), controlPoint2: CGPointMake(133.2, 91.34))
        bezierPath.addCurveToPoint(CGPointMake(94.7, 5.04), controlPoint1: CGPointMake(120.6, 57.24), controlPoint2: CGPointMake(95.4, 35.94))
        bezierPath.addCurveToPoint(CGPointMake(87.7, 1.24), controlPoint1: CGPointMake(94.6, 1.54), controlPoint2: CGPointMake(90.7, -0.66))
        bezierPath.addCurveToPoint(CGPointMake(17, 110.54), controlPoint1: CGPointMake(52.6, 22.34), controlPoint2: CGPointMake(7.1, 65.14))
        bezierPath.addCurveToPoint(CGPointMake(75.5, 164.14), controlPoint1: CGPointMake(19.6, 140.54), controlPoint2: CGPointMake(44.8, 164.14))
        bezierPath.addCurveToPoint(CGPointMake(120.4, 143.04), controlPoint1: CGPointMake(93.4, 164.14), controlPoint2: CGPointMake(109.5, 155.84))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        fillColor.setFill()
        bezierPath.fill()




        //// Group 7
        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(55.9, 97.74))
        bezier2Path.addCurveToPoint(CGPointMake(47, 88.84), controlPoint1: CGPointMake(51, 97.74), controlPoint2: CGPointMake(47, 93.74))
        bezier2Path.addCurveToPoint(CGPointMake(49.1, 86.74), controlPoint1: CGPointMake(47, 87.74), controlPoint2: CGPointMake(47.9, 86.74))
        bezier2Path.addCurveToPoint(CGPointMake(51.2, 88.84), controlPoint1: CGPointMake(50.3, 86.74), controlPoint2: CGPointMake(51.2, 87.64))
        bezier2Path.addCurveToPoint(CGPointMake(56, 93.64), controlPoint1: CGPointMake(51.2, 91.44), controlPoint2: CGPointMake(53.3, 93.64))
        bezier2Path.addCurveToPoint(CGPointMake(60.8, 88.84), controlPoint1: CGPointMake(58.6, 93.64), controlPoint2: CGPointMake(60.8, 91.54))
        bezier2Path.addCurveToPoint(CGPointMake(62.9, 86.74), controlPoint1: CGPointMake(60.8, 87.74), controlPoint2: CGPointMake(61.7, 86.74))
        bezier2Path.addCurveToPoint(CGPointMake(65, 88.84), controlPoint1: CGPointMake(64.1, 86.74), controlPoint2: CGPointMake(65, 87.64))
        bezier2Path.addCurveToPoint(CGPointMake(55.9, 97.74), controlPoint1: CGPointMake(64.9, 93.64), controlPoint2: CGPointMake(60.9, 97.74))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        fillColor2.setFill()
        bezier2Path.fill()




        //// Group 8
        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(94.3, 97.74))
        bezier3Path.addCurveToPoint(CGPointMake(85.4, 88.84), controlPoint1: CGPointMake(89.4, 97.74), controlPoint2: CGPointMake(85.4, 93.74))
        bezier3Path.addCurveToPoint(CGPointMake(87.5, 86.74), controlPoint1: CGPointMake(85.4, 87.74), controlPoint2: CGPointMake(86.3, 86.74))
        bezier3Path.addCurveToPoint(CGPointMake(89.6, 88.84), controlPoint1: CGPointMake(88.7, 86.74), controlPoint2: CGPointMake(89.6, 87.64))
        bezier3Path.addCurveToPoint(CGPointMake(94.4, 93.64), controlPoint1: CGPointMake(89.6, 91.44), controlPoint2: CGPointMake(91.7, 93.64))
        bezier3Path.addCurveToPoint(CGPointMake(99.2, 88.84), controlPoint1: CGPointMake(97, 93.64), controlPoint2: CGPointMake(99.2, 91.54))
        bezier3Path.addCurveToPoint(CGPointMake(101.3, 86.74), controlPoint1: CGPointMake(99.2, 87.74), controlPoint2: CGPointMake(100.1, 86.74))
        bezier3Path.addCurveToPoint(CGPointMake(103.4, 88.84), controlPoint1: CGPointMake(102.5, 86.74), controlPoint2: CGPointMake(103.4, 87.64))
        bezier3Path.addCurveToPoint(CGPointMake(94.3, 97.74), controlPoint1: CGPointMake(103.3, 93.64), controlPoint2: CGPointMake(99.3, 97.74))
        bezier3Path.closePath()
        bezier3Path.miterLimit = 4;

        fillColor2.setFill()
        bezier3Path.fill()




        //// Group 9
        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRectMake(67.9, 112.44, 14, 14))
        fillColor2.setFill()
        ovalPath.fill()




        //// Group 10
        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(74.9, 114.54))
        bezier4Path.addCurveToPoint(CGPointMake(81.8, 120.54), controlPoint1: CGPointMake(78.4, 114.54), controlPoint2: CGPointMake(81.3, 117.14))
        bezier4Path.addCurveToPoint(CGPointMake(81.9, 119.54), controlPoint1: CGPointMake(81.9, 120.24), controlPoint2: CGPointMake(81.9, 119.84))
        bezier4Path.addCurveToPoint(CGPointMake(74.9, 112.54), controlPoint1: CGPointMake(81.9, 115.64), controlPoint2: CGPointMake(78.8, 112.54))
        bezier4Path.addCurveToPoint(CGPointMake(67.9, 119.54), controlPoint1: CGPointMake(71, 112.54), controlPoint2: CGPointMake(67.9, 115.64))
        bezier4Path.addCurveToPoint(CGPointMake(68, 120.54), controlPoint1: CGPointMake(67.9, 119.94), controlPoint2: CGPointMake(67.9, 120.24))
        bezier4Path.addCurveToPoint(CGPointMake(74.9, 114.54), controlPoint1: CGPointMake(68.4, 117.14), controlPoint2: CGPointMake(71.3, 114.54))
        bezier4Path.closePath()
        bezier4Path.miterLimit = 4;

        fillColor3.setFill()
        bezier4Path.fill()




        //// Group 11
        //// Oval 2 Drawing
        let oval2Path = UIBezierPath(ovalInRect: CGRectMake(36.3, 101.84, 11, 11))
        fillColor4.setFill()
        oval2Path.fill()




        //// Group 12
        //// Oval 3 Drawing
        let oval3Path = UIBezierPath(ovalInRect: CGRectMake(102.7, 101.84, 11, 11))
        fillColor4.setFill()
        oval3Path.fill()




        //// Group 13
        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.moveToPoint(CGPointMake(115.7, 137.24))
        bezier5Path.addCurveToPoint(CGPointMake(113.2, 136.44), controlPoint1: CGPointMake(114.8, 137.24), controlPoint2: CGPointMake(114, 136.94))
        bezier5Path.addCurveToPoint(CGPointMake(112.5, 130.84), controlPoint1: CGPointMake(111.5, 135.04), controlPoint2: CGPointMake(111.1, 132.54))
        bezier5Path.addCurveToPoint(CGPointMake(118.1, 121.74), controlPoint1: CGPointMake(114.7, 128.04), controlPoint2: CGPointMake(116.6, 124.94))
        bezier5Path.addCurveToPoint(CGPointMake(123.4, 119.84), controlPoint1: CGPointMake(119, 119.74), controlPoint2: CGPointMake(121.4, 118.84))
        bezier5Path.addCurveToPoint(CGPointMake(125.3, 125.14), controlPoint1: CGPointMake(125.4, 120.74), controlPoint2: CGPointMake(126.3, 123.14))
        bezier5Path.addCurveToPoint(CGPointMake(118.8, 135.84), controlPoint1: CGPointMake(123.5, 128.94), controlPoint2: CGPointMake(121.4, 132.54))
        bezier5Path.addCurveToPoint(CGPointMake(115.7, 137.24), controlPoint1: CGPointMake(118.1, 136.74), controlPoint2: CGPointMake(116.9, 137.24))
        bezier5Path.closePath()
        bezier5Path.miterLimit = 4;

        fillColor5.setFill()
        bezier5Path.fill()




        //// Group 14
        //// Bezier 6 Drawing
        let bezier6Path = UIBezierPath()
        bezier6Path.moveToPoint(CGPointMake(75.5, 157.24))
        bezier6Path.addCurveToPoint(CGPointMake(45.2, 148.14), controlPoint1: CGPointMake(64.7, 157.24), controlPoint2: CGPointMake(54.2, 154.04))
        bezier6Path.addCurveToPoint(CGPointMake(44.1, 142.64), controlPoint1: CGPointMake(43.4, 146.94), controlPoint2: CGPointMake(42.9, 144.44))
        bezier6Path.addCurveToPoint(CGPointMake(49.6, 141.54), controlPoint1: CGPointMake(45.3, 140.84), controlPoint2: CGPointMake(47.8, 140.34))
        bezier6Path.addCurveToPoint(CGPointMake(75.5, 149.34), controlPoint1: CGPointMake(57.3, 146.64), controlPoint2: CGPointMake(66.2, 149.34))
        bezier6Path.addCurveToPoint(CGPointMake(94.6, 145.14), controlPoint1: CGPointMake(82.1, 149.34), controlPoint2: CGPointMake(88.5, 147.94))
        bezier6Path.addCurveToPoint(CGPointMake(103.2, 140.04), controlPoint1: CGPointMake(97.6, 143.74), controlPoint2: CGPointMake(100.5, 142.04))
        bezier6Path.addCurveToPoint(CGPointMake(108.8, 140.84), controlPoint1: CGPointMake(105, 138.74), controlPoint2: CGPointMake(107.5, 139.14))
        bezier6Path.addCurveToPoint(CGPointMake(108, 146.44), controlPoint1: CGPointMake(110.1, 142.64), controlPoint2: CGPointMake(109.7, 145.14))
        bezier6Path.addCurveToPoint(CGPointMake(98, 152.34), controlPoint1: CGPointMake(104.9, 148.74), controlPoint2: CGPointMake(101.5, 150.74))
        bezier6Path.addCurveToPoint(CGPointMake(75.5, 157.24), controlPoint1: CGPointMake(90.8, 155.64), controlPoint2: CGPointMake(83.3, 157.24))
        bezier6Path.closePath()
        bezier6Path.miterLimit = 4;

        fillColor5.setFill()
        bezier6Path.fill()
    }

    //// Generated Images

    public class var imageOfGoalieSleeping: UIImage {
        if Cache.imageOfGoalieSleeping != nil {
            return Cache.imageOfGoalieSleeping!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(150, 195), false, 0)
            GoalieStyleKit.drawGoalieSleeping()

        Cache.imageOfGoalieSleeping = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfGoalieSleeping!
    }

    //// Customization Infrastructure

    @IBOutlet var goalieSleepingTargets: [AnyObject]! {
        get { return Cache.goalieSleepingTargets }
        set {
            Cache.goalieSleepingTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: GoalieStyleKit.imageOfGoalieSleeping)
            }
        }
    }

}
